/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AppSubscriptionsRouteImport } from './routes/app/subscriptions'
import { Route as AppNewsRouteImport } from './routes/app/news'
import { Route as AppCoachesRouteImport } from './routes/app/coaches'
import { Route as AppBlogsRouteImport } from './routes/app/blogs'
import { Route as PublicContactUsRouteImport } from './routes/_public/contact-us'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as AppProgramsRouteRouteImport } from './routes/app/programs/route'
import { Route as AppSubscriptionsIndexRouteImport } from './routes/app/subscriptions/index'
import { Route as AppProgramsIndexRouteImport } from './routes/app/programs/index'
import { Route as AppNewsIndexRouteImport } from './routes/app/news/index'
import { Route as AppCoachesIndexRouteImport } from './routes/app/coaches.index'
import { Route as AppBlogsIndexRouteImport } from './routes/app/blogs.index'
import { Route as PublicProgramsIndexRouteImport } from './routes/_public/programs/index'
import { Route as AppProgramsSummerCampRouteImport } from './routes/app/programs/summer-camp'
import { Route as AppProgramsCompetitiveRouteImport } from './routes/app/programs/competitive'
import { Route as AppNewsCreateRouteImport } from './routes/app/news/create'
import { Route as AppNewsNewsIdRouteImport } from './routes/app/news/$newsId'
import { Route as AppCoachesNewRouteImport } from './routes/app/coaches.new'
import { Route as AppCoachesCoachIdRouteImport } from './routes/app/coaches.$coachId'
import { Route as AppBlogsNewRouteImport } from './routes/app/blogs.new'
import { Route as AppBlogsPostIdRouteImport } from './routes/app/blogs.$postId'
import { Route as PublicTeamCoachesRouteImport } from './routes/_public/team/coaches'
import { Route as PublicStoreTeamGearRouteImport } from './routes/_public/store/team-gear'
import { Route as PublicStoreSuitsForRentRouteImport } from './routes/_public/store/suits-for-rent'
import { Route as PublicProgramsSummerCampRouteImport } from './routes/_public/programs/summer-camp'
import { Route as PublicProgramsShowsRouteImport } from './routes/_public/programs/shows'
import { Route as PublicProgramsRecreationalRouteImport } from './routes/_public/programs/recreational'
import { Route as PublicProgramsFreeTry2026RouteImport } from './routes/_public/programs/free-try-2026'
import { Route as PublicProgramsCompetitiveRouteImport } from './routes/_public/programs/competitive'
import { Route as PublicProgramsBeginnerRouteImport } from './routes/_public/programs/beginner'
import { Route as PublicBoosterVolunteerRouteImport } from './routes/_public/booster/volunteer'
import { Route as PublicBoosterFundraisingRouteImport } from './routes/_public/booster/fundraising'
import { Route as PublicBoosterDonateRouteImport } from './routes/_public/booster/donate'
import { Route as PublicAthletesSportPsychologyRouteImport } from './routes/_public/athletes/sport-psychology'
import { Route as PublicAthletesSafetyRouteImport } from './routes/_public/athletes/safety'
import { Route as PublicAthletesKnoxingRouteImport } from './routes/_public/athletes/knoxing'
import { Route as PublicAthletesHealthRouteImport } from './routes/_public/athletes/health'
import { Route as PublicAthletesHallOfFameRouteImport } from './routes/_public/athletes/hall-of-fame'
import { Route as PublicTeamNewsIndexRouteImport } from './routes/_public/team/news/index'
import { Route as PublicTeamBlogIndexRouteImport } from './routes/_public/team/blog/index'
import { Route as PublicTeamNewsSlugRouteImport } from './routes/_public/team/news/$slug'
import { Route as PublicTeamBlogSlugRouteImport } from './routes/_public/team/blog/$slug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AppSubscriptionsRoute = AppSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNewsRoute = AppNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoachesRoute = AppCoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBlogsRoute = AppBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AppRouteRoute,
} as any)
const PublicContactUsRoute = PublicContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => PublicRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProgramsRouteRoute = AppProgramsRouteRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSubscriptionsIndexRoute = AppSubscriptionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSubscriptionsRoute,
} as any)
const AppProgramsIndexRoute = AppProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProgramsRouteRoute,
} as any)
const AppNewsIndexRoute = AppNewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNewsRoute,
} as any)
const AppCoachesIndexRoute = AppCoachesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCoachesRoute,
} as any)
const AppBlogsIndexRoute = AppBlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBlogsRoute,
} as any)
const PublicProgramsIndexRoute = PublicProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => PublicRoute,
} as any)
const AppProgramsSummerCampRoute = AppProgramsSummerCampRouteImport.update({
  id: '/summer-camp',
  path: '/summer-camp',
  getParentRoute: () => AppProgramsRouteRoute,
} as any)
const AppProgramsCompetitiveRoute = AppProgramsCompetitiveRouteImport.update({
  id: '/competitive',
  path: '/competitive',
  getParentRoute: () => AppProgramsRouteRoute,
} as any)
const AppNewsCreateRoute = AppNewsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppNewsRoute,
} as any)
const AppNewsNewsIdRoute = AppNewsNewsIdRouteImport.update({
  id: '/$newsId',
  path: '/$newsId',
  getParentRoute: () => AppNewsRoute,
} as any)
const AppCoachesNewRoute = AppCoachesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppCoachesRoute,
} as any)
const AppCoachesCoachIdRoute = AppCoachesCoachIdRouteImport.update({
  id: '/$coachId',
  path: '/$coachId',
  getParentRoute: () => AppCoachesRoute,
} as any)
const AppBlogsNewRoute = AppBlogsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppBlogsRoute,
} as any)
const AppBlogsPostIdRoute = AppBlogsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AppBlogsRoute,
} as any)
const PublicTeamCoachesRoute = PublicTeamCoachesRouteImport.update({
  id: '/team/coaches',
  path: '/team/coaches',
  getParentRoute: () => PublicRoute,
} as any)
const PublicStoreTeamGearRoute = PublicStoreTeamGearRouteImport.update({
  id: '/store/team-gear',
  path: '/store/team-gear',
  getParentRoute: () => PublicRoute,
} as any)
const PublicStoreSuitsForRentRoute = PublicStoreSuitsForRentRouteImport.update({
  id: '/store/suits-for-rent',
  path: '/store/suits-for-rent',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProgramsSummerCampRoute =
  PublicProgramsSummerCampRouteImport.update({
    id: '/programs/summer-camp',
    path: '/programs/summer-camp',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicProgramsShowsRoute = PublicProgramsShowsRouteImport.update({
  id: '/programs/shows',
  path: '/programs/shows',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProgramsRecreationalRoute =
  PublicProgramsRecreationalRouteImport.update({
    id: '/programs/recreational',
    path: '/programs/recreational',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicProgramsFreeTry2026Route =
  PublicProgramsFreeTry2026RouteImport.update({
    id: '/programs/free-try-2026',
    path: '/programs/free-try-2026',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicProgramsCompetitiveRoute =
  PublicProgramsCompetitiveRouteImport.update({
    id: '/programs/competitive',
    path: '/programs/competitive',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicProgramsBeginnerRoute = PublicProgramsBeginnerRouteImport.update({
  id: '/programs/beginner',
  path: '/programs/beginner',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBoosterVolunteerRoute = PublicBoosterVolunteerRouteImport.update({
  id: '/booster/volunteer',
  path: '/booster/volunteer',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBoosterFundraisingRoute =
  PublicBoosterFundraisingRouteImport.update({
    id: '/booster/fundraising',
    path: '/booster/fundraising',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicBoosterDonateRoute = PublicBoosterDonateRouteImport.update({
  id: '/booster/donate',
  path: '/booster/donate',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAthletesSportPsychologyRoute =
  PublicAthletesSportPsychologyRouteImport.update({
    id: '/athletes/sport-psychology',
    path: '/athletes/sport-psychology',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicAthletesSafetyRoute = PublicAthletesSafetyRouteImport.update({
  id: '/athletes/safety',
  path: '/athletes/safety',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAthletesKnoxingRoute = PublicAthletesKnoxingRouteImport.update({
  id: '/athletes/knoxing',
  path: '/athletes/knoxing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAthletesHealthRoute = PublicAthletesHealthRouteImport.update({
  id: '/athletes/health',
  path: '/athletes/health',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAthletesHallOfFameRoute =
  PublicAthletesHallOfFameRouteImport.update({
    id: '/athletes/hall-of-fame',
    path: '/athletes/hall-of-fame',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicTeamNewsIndexRoute = PublicTeamNewsIndexRouteImport.update({
  id: '/team/news/',
  path: '/team/news/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTeamBlogIndexRoute = PublicTeamBlogIndexRouteImport.update({
  id: '/team/blog/',
  path: '/team/blog/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTeamNewsSlugRoute = PublicTeamNewsSlugRouteImport.update({
  id: '/team/news/$slug',
  path: '/team/news/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTeamBlogSlugRoute = PublicTeamBlogSlugRouteImport.update({
  id: '/team/blog/$slug',
  path: '/team/blog/$slug',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteRouteWithChildren
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/app/programs': typeof AppProgramsRouteRouteWithChildren
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/contact-us': typeof PublicContactUsRoute
  '/app/blogs': typeof AppBlogsRouteWithChildren
  '/app/coaches': typeof AppCoachesRouteWithChildren
  '/app/news': typeof AppNewsRouteWithChildren
  '/app/subscriptions': typeof AppSubscriptionsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/athletes/hall-of-fame': typeof PublicAthletesHallOfFameRoute
  '/athletes/health': typeof PublicAthletesHealthRoute
  '/athletes/knoxing': typeof PublicAthletesKnoxingRoute
  '/athletes/safety': typeof PublicAthletesSafetyRoute
  '/athletes/sport-psychology': typeof PublicAthletesSportPsychologyRoute
  '/booster/donate': typeof PublicBoosterDonateRoute
  '/booster/fundraising': typeof PublicBoosterFundraisingRoute
  '/booster/volunteer': typeof PublicBoosterVolunteerRoute
  '/programs/beginner': typeof PublicProgramsBeginnerRoute
  '/programs/competitive': typeof PublicProgramsCompetitiveRoute
  '/programs/free-try-2026': typeof PublicProgramsFreeTry2026Route
  '/programs/recreational': typeof PublicProgramsRecreationalRoute
  '/programs/shows': typeof PublicProgramsShowsRoute
  '/programs/summer-camp': typeof PublicProgramsSummerCampRoute
  '/store/suits-for-rent': typeof PublicStoreSuitsForRentRoute
  '/store/team-gear': typeof PublicStoreTeamGearRoute
  '/team/coaches': typeof PublicTeamCoachesRoute
  '/app/blogs/$postId': typeof AppBlogsPostIdRoute
  '/app/blogs/new': typeof AppBlogsNewRoute
  '/app/coaches/$coachId': typeof AppCoachesCoachIdRoute
  '/app/coaches/new': typeof AppCoachesNewRoute
  '/app/news/$newsId': typeof AppNewsNewsIdRoute
  '/app/news/create': typeof AppNewsCreateRoute
  '/app/programs/competitive': typeof AppProgramsCompetitiveRoute
  '/app/programs/summer-camp': typeof AppProgramsSummerCampRoute
  '/programs/': typeof PublicProgramsIndexRoute
  '/app/blogs/': typeof AppBlogsIndexRoute
  '/app/coaches/': typeof AppCoachesIndexRoute
  '/app/news/': typeof AppNewsIndexRoute
  '/app/programs/': typeof AppProgramsIndexRoute
  '/app/subscriptions/': typeof AppSubscriptionsIndexRoute
  '/team/blog/$slug': typeof PublicTeamBlogSlugRoute
  '/team/news/$slug': typeof PublicTeamNewsSlugRoute
  '/team/blog/': typeof PublicTeamBlogIndexRoute
  '/team/news/': typeof PublicTeamNewsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/contact-us': typeof PublicContactUsRoute
  '/': typeof PublicIndexRoute
  '/app': typeof AppIndexRoute
  '/athletes/hall-of-fame': typeof PublicAthletesHallOfFameRoute
  '/athletes/health': typeof PublicAthletesHealthRoute
  '/athletes/knoxing': typeof PublicAthletesKnoxingRoute
  '/athletes/safety': typeof PublicAthletesSafetyRoute
  '/athletes/sport-psychology': typeof PublicAthletesSportPsychologyRoute
  '/booster/donate': typeof PublicBoosterDonateRoute
  '/booster/fundraising': typeof PublicBoosterFundraisingRoute
  '/booster/volunteer': typeof PublicBoosterVolunteerRoute
  '/programs/beginner': typeof PublicProgramsBeginnerRoute
  '/programs/competitive': typeof PublicProgramsCompetitiveRoute
  '/programs/free-try-2026': typeof PublicProgramsFreeTry2026Route
  '/programs/recreational': typeof PublicProgramsRecreationalRoute
  '/programs/shows': typeof PublicProgramsShowsRoute
  '/programs/summer-camp': typeof PublicProgramsSummerCampRoute
  '/store/suits-for-rent': typeof PublicStoreSuitsForRentRoute
  '/store/team-gear': typeof PublicStoreTeamGearRoute
  '/team/coaches': typeof PublicTeamCoachesRoute
  '/app/blogs/$postId': typeof AppBlogsPostIdRoute
  '/app/blogs/new': typeof AppBlogsNewRoute
  '/app/coaches/$coachId': typeof AppCoachesCoachIdRoute
  '/app/coaches/new': typeof AppCoachesNewRoute
  '/app/news/$newsId': typeof AppNewsNewsIdRoute
  '/app/news/create': typeof AppNewsCreateRoute
  '/app/programs/competitive': typeof AppProgramsCompetitiveRoute
  '/app/programs/summer-camp': typeof AppProgramsSummerCampRoute
  '/programs': typeof PublicProgramsIndexRoute
  '/app/blogs': typeof AppBlogsIndexRoute
  '/app/coaches': typeof AppCoachesIndexRoute
  '/app/news': typeof AppNewsIndexRoute
  '/app/programs': typeof AppProgramsIndexRoute
  '/app/subscriptions': typeof AppSubscriptionsIndexRoute
  '/team/blog/$slug': typeof PublicTeamBlogSlugRoute
  '/team/news/$slug': typeof PublicTeamNewsSlugRoute
  '/team/blog': typeof PublicTeamBlogIndexRoute
  '/team/news': typeof PublicTeamNewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/app/programs': typeof AppProgramsRouteRouteWithChildren
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_public/contact-us': typeof PublicContactUsRoute
  '/app/blogs': typeof AppBlogsRouteWithChildren
  '/app/coaches': typeof AppCoachesRouteWithChildren
  '/app/news': typeof AppNewsRouteWithChildren
  '/app/subscriptions': typeof AppSubscriptionsRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/app/': typeof AppIndexRoute
  '/_public/athletes/hall-of-fame': typeof PublicAthletesHallOfFameRoute
  '/_public/athletes/health': typeof PublicAthletesHealthRoute
  '/_public/athletes/knoxing': typeof PublicAthletesKnoxingRoute
  '/_public/athletes/safety': typeof PublicAthletesSafetyRoute
  '/_public/athletes/sport-psychology': typeof PublicAthletesSportPsychologyRoute
  '/_public/booster/donate': typeof PublicBoosterDonateRoute
  '/_public/booster/fundraising': typeof PublicBoosterFundraisingRoute
  '/_public/booster/volunteer': typeof PublicBoosterVolunteerRoute
  '/_public/programs/beginner': typeof PublicProgramsBeginnerRoute
  '/_public/programs/competitive': typeof PublicProgramsCompetitiveRoute
  '/_public/programs/free-try-2026': typeof PublicProgramsFreeTry2026Route
  '/_public/programs/recreational': typeof PublicProgramsRecreationalRoute
  '/_public/programs/shows': typeof PublicProgramsShowsRoute
  '/_public/programs/summer-camp': typeof PublicProgramsSummerCampRoute
  '/_public/store/suits-for-rent': typeof PublicStoreSuitsForRentRoute
  '/_public/store/team-gear': typeof PublicStoreTeamGearRoute
  '/_public/team/coaches': typeof PublicTeamCoachesRoute
  '/app/blogs/$postId': typeof AppBlogsPostIdRoute
  '/app/blogs/new': typeof AppBlogsNewRoute
  '/app/coaches/$coachId': typeof AppCoachesCoachIdRoute
  '/app/coaches/new': typeof AppCoachesNewRoute
  '/app/news/$newsId': typeof AppNewsNewsIdRoute
  '/app/news/create': typeof AppNewsCreateRoute
  '/app/programs/competitive': typeof AppProgramsCompetitiveRoute
  '/app/programs/summer-camp': typeof AppProgramsSummerCampRoute
  '/_public/programs/': typeof PublicProgramsIndexRoute
  '/app/blogs/': typeof AppBlogsIndexRoute
  '/app/coaches/': typeof AppCoachesIndexRoute
  '/app/news/': typeof AppNewsIndexRoute
  '/app/programs/': typeof AppProgramsIndexRoute
  '/app/subscriptions/': typeof AppSubscriptionsIndexRoute
  '/_public/team/blog/$slug': typeof PublicTeamBlogSlugRoute
  '/_public/team/news/$slug': typeof PublicTeamNewsSlugRoute
  '/_public/team/blog/': typeof PublicTeamBlogIndexRoute
  '/_public/team/news/': typeof PublicTeamNewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/'
    | '/login'
    | '/app/programs'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/contact-us'
    | '/app/blogs'
    | '/app/coaches'
    | '/app/news'
    | '/app/subscriptions'
    | '/app/'
    | '/athletes/hall-of-fame'
    | '/athletes/health'
    | '/athletes/knoxing'
    | '/athletes/safety'
    | '/athletes/sport-psychology'
    | '/booster/donate'
    | '/booster/fundraising'
    | '/booster/volunteer'
    | '/programs/beginner'
    | '/programs/competitive'
    | '/programs/free-try-2026'
    | '/programs/recreational'
    | '/programs/shows'
    | '/programs/summer-camp'
    | '/store/suits-for-rent'
    | '/store/team-gear'
    | '/team/coaches'
    | '/app/blogs/$postId'
    | '/app/blogs/new'
    | '/app/coaches/$coachId'
    | '/app/coaches/new'
    | '/app/news/$newsId'
    | '/app/news/create'
    | '/app/programs/competitive'
    | '/app/programs/summer-camp'
    | '/programs/'
    | '/app/blogs/'
    | '/app/coaches/'
    | '/app/news/'
    | '/app/programs/'
    | '/app/subscriptions/'
    | '/team/blog/$slug'
    | '/team/news/$slug'
    | '/team/blog/'
    | '/team/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/contact-us'
    | '/'
    | '/app'
    | '/athletes/hall-of-fame'
    | '/athletes/health'
    | '/athletes/knoxing'
    | '/athletes/safety'
    | '/athletes/sport-psychology'
    | '/booster/donate'
    | '/booster/fundraising'
    | '/booster/volunteer'
    | '/programs/beginner'
    | '/programs/competitive'
    | '/programs/free-try-2026'
    | '/programs/recreational'
    | '/programs/shows'
    | '/programs/summer-camp'
    | '/store/suits-for-rent'
    | '/store/team-gear'
    | '/team/coaches'
    | '/app/blogs/$postId'
    | '/app/blogs/new'
    | '/app/coaches/$coachId'
    | '/app/coaches/new'
    | '/app/news/$newsId'
    | '/app/news/create'
    | '/app/programs/competitive'
    | '/app/programs/summer-camp'
    | '/programs'
    | '/app/blogs'
    | '/app/coaches'
    | '/app/news'
    | '/app/programs'
    | '/app/subscriptions'
    | '/team/blog/$slug'
    | '/team/news/$slug'
    | '/team/blog'
    | '/team/news'
  id:
    | '__root__'
    | '/app'
    | '/_public'
    | '/login'
    | '/app/programs'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_public/contact-us'
    | '/app/blogs'
    | '/app/coaches'
    | '/app/news'
    | '/app/subscriptions'
    | '/_public/'
    | '/app/'
    | '/_public/athletes/hall-of-fame'
    | '/_public/athletes/health'
    | '/_public/athletes/knoxing'
    | '/_public/athletes/safety'
    | '/_public/athletes/sport-psychology'
    | '/_public/booster/donate'
    | '/_public/booster/fundraising'
    | '/_public/booster/volunteer'
    | '/_public/programs/beginner'
    | '/_public/programs/competitive'
    | '/_public/programs/free-try-2026'
    | '/_public/programs/recreational'
    | '/_public/programs/shows'
    | '/_public/programs/summer-camp'
    | '/_public/store/suits-for-rent'
    | '/_public/store/team-gear'
    | '/_public/team/coaches'
    | '/app/blogs/$postId'
    | '/app/blogs/new'
    | '/app/coaches/$coachId'
    | '/app/coaches/new'
    | '/app/news/$newsId'
    | '/app/news/create'
    | '/app/programs/competitive'
    | '/app/programs/summer-camp'
    | '/_public/programs/'
    | '/app/blogs/'
    | '/app/coaches/'
    | '/app/news/'
    | '/app/programs/'
    | '/app/subscriptions/'
    | '/_public/team/blog/$slug'
    | '/_public/team/news/$slug'
    | '/_public/team/blog/'
    | '/_public/team/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/app/subscriptions': {
      id: '/app/subscriptions'
      path: '/subscriptions'
      fullPath: '/app/subscriptions'
      preLoaderRoute: typeof AppSubscriptionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/news': {
      id: '/app/news'
      path: '/news'
      fullPath: '/app/news'
      preLoaderRoute: typeof AppNewsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/coaches': {
      id: '/app/coaches'
      path: '/coaches'
      fullPath: '/app/coaches'
      preLoaderRoute: typeof AppCoachesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/blogs': {
      id: '/app/blogs'
      path: '/blogs'
      fullPath: '/app/blogs'
      preLoaderRoute: typeof AppBlogsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_public/contact-us': {
      id: '/_public/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof PublicContactUsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/programs': {
      id: '/app/programs'
      path: '/programs'
      fullPath: '/app/programs'
      preLoaderRoute: typeof AppProgramsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/subscriptions/': {
      id: '/app/subscriptions/'
      path: '/'
      fullPath: '/app/subscriptions/'
      preLoaderRoute: typeof AppSubscriptionsIndexRouteImport
      parentRoute: typeof AppSubscriptionsRoute
    }
    '/app/programs/': {
      id: '/app/programs/'
      path: '/'
      fullPath: '/app/programs/'
      preLoaderRoute: typeof AppProgramsIndexRouteImport
      parentRoute: typeof AppProgramsRouteRoute
    }
    '/app/news/': {
      id: '/app/news/'
      path: '/'
      fullPath: '/app/news/'
      preLoaderRoute: typeof AppNewsIndexRouteImport
      parentRoute: typeof AppNewsRoute
    }
    '/app/coaches/': {
      id: '/app/coaches/'
      path: '/'
      fullPath: '/app/coaches/'
      preLoaderRoute: typeof AppCoachesIndexRouteImport
      parentRoute: typeof AppCoachesRoute
    }
    '/app/blogs/': {
      id: '/app/blogs/'
      path: '/'
      fullPath: '/app/blogs/'
      preLoaderRoute: typeof AppBlogsIndexRouteImport
      parentRoute: typeof AppBlogsRoute
    }
    '/_public/programs/': {
      id: '/_public/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof PublicProgramsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/app/programs/summer-camp': {
      id: '/app/programs/summer-camp'
      path: '/summer-camp'
      fullPath: '/app/programs/summer-camp'
      preLoaderRoute: typeof AppProgramsSummerCampRouteImport
      parentRoute: typeof AppProgramsRouteRoute
    }
    '/app/programs/competitive': {
      id: '/app/programs/competitive'
      path: '/competitive'
      fullPath: '/app/programs/competitive'
      preLoaderRoute: typeof AppProgramsCompetitiveRouteImport
      parentRoute: typeof AppProgramsRouteRoute
    }
    '/app/news/create': {
      id: '/app/news/create'
      path: '/create'
      fullPath: '/app/news/create'
      preLoaderRoute: typeof AppNewsCreateRouteImport
      parentRoute: typeof AppNewsRoute
    }
    '/app/news/$newsId': {
      id: '/app/news/$newsId'
      path: '/$newsId'
      fullPath: '/app/news/$newsId'
      preLoaderRoute: typeof AppNewsNewsIdRouteImport
      parentRoute: typeof AppNewsRoute
    }
    '/app/coaches/new': {
      id: '/app/coaches/new'
      path: '/new'
      fullPath: '/app/coaches/new'
      preLoaderRoute: typeof AppCoachesNewRouteImport
      parentRoute: typeof AppCoachesRoute
    }
    '/app/coaches/$coachId': {
      id: '/app/coaches/$coachId'
      path: '/$coachId'
      fullPath: '/app/coaches/$coachId'
      preLoaderRoute: typeof AppCoachesCoachIdRouteImport
      parentRoute: typeof AppCoachesRoute
    }
    '/app/blogs/new': {
      id: '/app/blogs/new'
      path: '/new'
      fullPath: '/app/blogs/new'
      preLoaderRoute: typeof AppBlogsNewRouteImport
      parentRoute: typeof AppBlogsRoute
    }
    '/app/blogs/$postId': {
      id: '/app/blogs/$postId'
      path: '/$postId'
      fullPath: '/app/blogs/$postId'
      preLoaderRoute: typeof AppBlogsPostIdRouteImport
      parentRoute: typeof AppBlogsRoute
    }
    '/_public/team/coaches': {
      id: '/_public/team/coaches'
      path: '/team/coaches'
      fullPath: '/team/coaches'
      preLoaderRoute: typeof PublicTeamCoachesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/store/team-gear': {
      id: '/_public/store/team-gear'
      path: '/store/team-gear'
      fullPath: '/store/team-gear'
      preLoaderRoute: typeof PublicStoreTeamGearRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/store/suits-for-rent': {
      id: '/_public/store/suits-for-rent'
      path: '/store/suits-for-rent'
      fullPath: '/store/suits-for-rent'
      preLoaderRoute: typeof PublicStoreSuitsForRentRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/programs/summer-camp': {
      id: '/_public/programs/summer-camp'
      path: '/programs/summer-camp'
      fullPath: '/programs/summer-camp'
      preLoaderRoute: typeof PublicProgramsSummerCampRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/programs/shows': {
      id: '/_public/programs/shows'
      path: '/programs/shows'
      fullPath: '/programs/shows'
      preLoaderRoute: typeof PublicProgramsShowsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/programs/recreational': {
      id: '/_public/programs/recreational'
      path: '/programs/recreational'
      fullPath: '/programs/recreational'
      preLoaderRoute: typeof PublicProgramsRecreationalRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/programs/free-try-2026': {
      id: '/_public/programs/free-try-2026'
      path: '/programs/free-try-2026'
      fullPath: '/programs/free-try-2026'
      preLoaderRoute: typeof PublicProgramsFreeTry2026RouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/programs/competitive': {
      id: '/_public/programs/competitive'
      path: '/programs/competitive'
      fullPath: '/programs/competitive'
      preLoaderRoute: typeof PublicProgramsCompetitiveRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/programs/beginner': {
      id: '/_public/programs/beginner'
      path: '/programs/beginner'
      fullPath: '/programs/beginner'
      preLoaderRoute: typeof PublicProgramsBeginnerRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/booster/volunteer': {
      id: '/_public/booster/volunteer'
      path: '/booster/volunteer'
      fullPath: '/booster/volunteer'
      preLoaderRoute: typeof PublicBoosterVolunteerRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/booster/fundraising': {
      id: '/_public/booster/fundraising'
      path: '/booster/fundraising'
      fullPath: '/booster/fundraising'
      preLoaderRoute: typeof PublicBoosterFundraisingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/booster/donate': {
      id: '/_public/booster/donate'
      path: '/booster/donate'
      fullPath: '/booster/donate'
      preLoaderRoute: typeof PublicBoosterDonateRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/athletes/sport-psychology': {
      id: '/_public/athletes/sport-psychology'
      path: '/athletes/sport-psychology'
      fullPath: '/athletes/sport-psychology'
      preLoaderRoute: typeof PublicAthletesSportPsychologyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/athletes/safety': {
      id: '/_public/athletes/safety'
      path: '/athletes/safety'
      fullPath: '/athletes/safety'
      preLoaderRoute: typeof PublicAthletesSafetyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/athletes/knoxing': {
      id: '/_public/athletes/knoxing'
      path: '/athletes/knoxing'
      fullPath: '/athletes/knoxing'
      preLoaderRoute: typeof PublicAthletesKnoxingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/athletes/health': {
      id: '/_public/athletes/health'
      path: '/athletes/health'
      fullPath: '/athletes/health'
      preLoaderRoute: typeof PublicAthletesHealthRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/athletes/hall-of-fame': {
      id: '/_public/athletes/hall-of-fame'
      path: '/athletes/hall-of-fame'
      fullPath: '/athletes/hall-of-fame'
      preLoaderRoute: typeof PublicAthletesHallOfFameRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/team/news/': {
      id: '/_public/team/news/'
      path: '/team/news'
      fullPath: '/team/news/'
      preLoaderRoute: typeof PublicTeamNewsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/team/blog/': {
      id: '/_public/team/blog/'
      path: '/team/blog'
      fullPath: '/team/blog/'
      preLoaderRoute: typeof PublicTeamBlogIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/team/news/$slug': {
      id: '/_public/team/news/$slug'
      path: '/team/news/$slug'
      fullPath: '/team/news/$slug'
      preLoaderRoute: typeof PublicTeamNewsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/team/blog/$slug': {
      id: '/_public/team/blog/$slug'
      path: '/team/blog/$slug'
      fullPath: '/team/blog/$slug'
      preLoaderRoute: typeof PublicTeamBlogSlugRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface AppProgramsRouteRouteChildren {
  AppProgramsCompetitiveRoute: typeof AppProgramsCompetitiveRoute
  AppProgramsSummerCampRoute: typeof AppProgramsSummerCampRoute
  AppProgramsIndexRoute: typeof AppProgramsIndexRoute
}

const AppProgramsRouteRouteChildren: AppProgramsRouteRouteChildren = {
  AppProgramsCompetitiveRoute: AppProgramsCompetitiveRoute,
  AppProgramsSummerCampRoute: AppProgramsSummerCampRoute,
  AppProgramsIndexRoute: AppProgramsIndexRoute,
}

const AppProgramsRouteRouteWithChildren =
  AppProgramsRouteRoute._addFileChildren(AppProgramsRouteRouteChildren)

interface AppBlogsRouteChildren {
  AppBlogsPostIdRoute: typeof AppBlogsPostIdRoute
  AppBlogsNewRoute: typeof AppBlogsNewRoute
  AppBlogsIndexRoute: typeof AppBlogsIndexRoute
}

const AppBlogsRouteChildren: AppBlogsRouteChildren = {
  AppBlogsPostIdRoute: AppBlogsPostIdRoute,
  AppBlogsNewRoute: AppBlogsNewRoute,
  AppBlogsIndexRoute: AppBlogsIndexRoute,
}

const AppBlogsRouteWithChildren = AppBlogsRoute._addFileChildren(
  AppBlogsRouteChildren,
)

interface AppCoachesRouteChildren {
  AppCoachesCoachIdRoute: typeof AppCoachesCoachIdRoute
  AppCoachesNewRoute: typeof AppCoachesNewRoute
  AppCoachesIndexRoute: typeof AppCoachesIndexRoute
}

const AppCoachesRouteChildren: AppCoachesRouteChildren = {
  AppCoachesCoachIdRoute: AppCoachesCoachIdRoute,
  AppCoachesNewRoute: AppCoachesNewRoute,
  AppCoachesIndexRoute: AppCoachesIndexRoute,
}

const AppCoachesRouteWithChildren = AppCoachesRoute._addFileChildren(
  AppCoachesRouteChildren,
)

interface AppNewsRouteChildren {
  AppNewsNewsIdRoute: typeof AppNewsNewsIdRoute
  AppNewsCreateRoute: typeof AppNewsCreateRoute
  AppNewsIndexRoute: typeof AppNewsIndexRoute
}

const AppNewsRouteChildren: AppNewsRouteChildren = {
  AppNewsNewsIdRoute: AppNewsNewsIdRoute,
  AppNewsCreateRoute: AppNewsCreateRoute,
  AppNewsIndexRoute: AppNewsIndexRoute,
}

const AppNewsRouteWithChildren =
  AppNewsRoute._addFileChildren(AppNewsRouteChildren)

interface AppSubscriptionsRouteChildren {
  AppSubscriptionsIndexRoute: typeof AppSubscriptionsIndexRoute
}

const AppSubscriptionsRouteChildren: AppSubscriptionsRouteChildren = {
  AppSubscriptionsIndexRoute: AppSubscriptionsIndexRoute,
}

const AppSubscriptionsRouteWithChildren =
  AppSubscriptionsRoute._addFileChildren(AppSubscriptionsRouteChildren)

interface AppRouteRouteChildren {
  AppProgramsRouteRoute: typeof AppProgramsRouteRouteWithChildren
  AppBlogsRoute: typeof AppBlogsRouteWithChildren
  AppCoachesRoute: typeof AppCoachesRouteWithChildren
  AppNewsRoute: typeof AppNewsRouteWithChildren
  AppSubscriptionsRoute: typeof AppSubscriptionsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProgramsRouteRoute: AppProgramsRouteRouteWithChildren,
  AppBlogsRoute: AppBlogsRouteWithChildren,
  AppCoachesRoute: AppCoachesRouteWithChildren,
  AppNewsRoute: AppNewsRouteWithChildren,
  AppSubscriptionsRoute: AppSubscriptionsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface PublicRouteChildren {
  PublicContactUsRoute: typeof PublicContactUsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicAthletesHallOfFameRoute: typeof PublicAthletesHallOfFameRoute
  PublicAthletesHealthRoute: typeof PublicAthletesHealthRoute
  PublicAthletesKnoxingRoute: typeof PublicAthletesKnoxingRoute
  PublicAthletesSafetyRoute: typeof PublicAthletesSafetyRoute
  PublicAthletesSportPsychologyRoute: typeof PublicAthletesSportPsychologyRoute
  PublicBoosterDonateRoute: typeof PublicBoosterDonateRoute
  PublicBoosterFundraisingRoute: typeof PublicBoosterFundraisingRoute
  PublicBoosterVolunteerRoute: typeof PublicBoosterVolunteerRoute
  PublicProgramsBeginnerRoute: typeof PublicProgramsBeginnerRoute
  PublicProgramsCompetitiveRoute: typeof PublicProgramsCompetitiveRoute
  PublicProgramsFreeTry2026Route: typeof PublicProgramsFreeTry2026Route
  PublicProgramsRecreationalRoute: typeof PublicProgramsRecreationalRoute
  PublicProgramsShowsRoute: typeof PublicProgramsShowsRoute
  PublicProgramsSummerCampRoute: typeof PublicProgramsSummerCampRoute
  PublicStoreSuitsForRentRoute: typeof PublicStoreSuitsForRentRoute
  PublicStoreTeamGearRoute: typeof PublicStoreTeamGearRoute
  PublicTeamCoachesRoute: typeof PublicTeamCoachesRoute
  PublicProgramsIndexRoute: typeof PublicProgramsIndexRoute
  PublicTeamBlogSlugRoute: typeof PublicTeamBlogSlugRoute
  PublicTeamNewsSlugRoute: typeof PublicTeamNewsSlugRoute
  PublicTeamBlogIndexRoute: typeof PublicTeamBlogIndexRoute
  PublicTeamNewsIndexRoute: typeof PublicTeamNewsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicContactUsRoute: PublicContactUsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicAthletesHallOfFameRoute: PublicAthletesHallOfFameRoute,
  PublicAthletesHealthRoute: PublicAthletesHealthRoute,
  PublicAthletesKnoxingRoute: PublicAthletesKnoxingRoute,
  PublicAthletesSafetyRoute: PublicAthletesSafetyRoute,
  PublicAthletesSportPsychologyRoute: PublicAthletesSportPsychologyRoute,
  PublicBoosterDonateRoute: PublicBoosterDonateRoute,
  PublicBoosterFundraisingRoute: PublicBoosterFundraisingRoute,
  PublicBoosterVolunteerRoute: PublicBoosterVolunteerRoute,
  PublicProgramsBeginnerRoute: PublicProgramsBeginnerRoute,
  PublicProgramsCompetitiveRoute: PublicProgramsCompetitiveRoute,
  PublicProgramsFreeTry2026Route: PublicProgramsFreeTry2026Route,
  PublicProgramsRecreationalRoute: PublicProgramsRecreationalRoute,
  PublicProgramsShowsRoute: PublicProgramsShowsRoute,
  PublicProgramsSummerCampRoute: PublicProgramsSummerCampRoute,
  PublicStoreSuitsForRentRoute: PublicStoreSuitsForRentRoute,
  PublicStoreTeamGearRoute: PublicStoreTeamGearRoute,
  PublicTeamCoachesRoute: PublicTeamCoachesRoute,
  PublicProgramsIndexRoute: PublicProgramsIndexRoute,
  PublicTeamBlogSlugRoute: PublicTeamBlogSlugRoute,
  PublicTeamNewsSlugRoute: PublicTeamNewsSlugRoute,
  PublicTeamBlogIndexRoute: PublicTeamBlogIndexRoute,
  PublicTeamNewsIndexRoute: PublicTeamNewsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
